name: CI/CD for Blazor App

on:
  push:
    branches:
      - main       # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main       # Trigger the workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # or 'windows-latest' depending on your app requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'   # Use the appropriate .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the Blazor App
      run: dotnet build --configuration Release

    - name: Publish the Blazor App to a folder
      run: dotnet publish -c Release -o ${{ github.workspace }}/output

  deploy:
    runs-on: ubuntu-latest
    needs: build    # Only runs after the 'build' job completes successfully

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages     # Branch where your GitHub Pages is hosted
        folder: ${{ github.workspace }}/output/www  # The folder where your built app resides
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the deploy process


