name: CI/CD for Blazor App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can use 'windows-latest' or 'macos-latest' based on your project requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Use the .NET version that your Blazor app requires

    - name: Restore dependencies
      run: dotnet restore  # Restore NuGet dependencies

    - name: Build the Blazor app
      run: dotnet build --configuration Release  # Build the app in Release configuration

    - name: Publish the Blazor app to a folder
      run: dotnet publish -c Release -o ${{ github.workspace }}/output  # Publish app to 'output' folder

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job, so it will run after it completes successfully

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4  # Action to deploy to GitHub Pages
      with:
        branch: gh-pages  # The branch where the app will be deployed
        folder: ${{ github.workspace }}/output/www  # Folder containing the published Blazor app's static files
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

